### ISSUE TITLE
SID_070: SoC-integrated PCIe devices MAY support programmable BAR registers.

### ISSUE THREAD

**Issue by andreiw** [riscv-non-isa/server-soc#21]
If I understand correctly, this is a BAR that ignores any writes ("fixed in position"). Similar to what was seen on Pass 1 Cavium ThunderX CN88xx devices, and I recall this being non-standard (it was replaced with fixed EAs in shipping Si). Presumably such systems would also have strange switches (wrt their aperture behavior).

Is there a particular benefit to allowing this behavior? It will mean an OS has to be able to tolerate such behavior (and work around it from the perspective of supporting full resource reconfiguration).

**Comment by ved-rivos** [comment]
Updated in https://github.com/riscv-non-isa/server-soc/pull/26/commits/7169129929867fd6ccc0d66f9bd35282d57ea503

**Comment by andreiw** [comment]
Lgtm
