### ISSUE TITLE
Watchdog?

### ISSUE THREAD

**Issue by andreiw** [riscv-non-isa/server-soc#47]
Was this ever discussed? Should there be a standardized hardware watchdog? IIRC this isn't something that exists in standard form on x86 (e.g. an OS may use a timer source + NMI), but AArch64 server systems do require a watchdog, so from that standpoint if software is ported from AArch64 to RV64 servers, this appears as a gap.

**Comment by ved-rivos** [comment]
There was a proposed spec a few years ago for a standard watchdog but it was argued against in favor of abstracting it behind the SBI. This would also make it easier to virtualize.
